# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 'https://JihuiTanUchicago.github.io/'
baseurl:             'AppDevII/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Todd Tan
  url:               https://www.linkedin.com/in/jihui-tan-9924711aa/
  email:             tanjihui@uchicago.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
